
server:
  port: 8082  
spring:
  application:
    name: websocket-service
  web-application-type: reactive
    
  # RabbitMQ Configuration for Message Broker
  rabbitmq:
    host: ${RABBITMQ_HOST:ip172-18-0-15-d65f9q291nsg00e23itg-5671.direct.labs.play-with-docker.com}
    port: ${RABBITMQ_PORT:5671}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    
logging:
  level:
    com.agarg.securecollab: DEBUG
    org.springframework: INFO

# WebSocket Configuration
websocket:
  max-text-message-size: 8192000
  max-binary-message-size: 8192000
  idle-timeout: 3600000