
server:
  port: 8080

spring:
  application:
    name: gateway-service
  web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: chat-service
          uri: http://ip172-18-0-15-d65f9q291nsg00e23itg-8081.direct.labs.play-with-docker.com
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=1
        - id: websocket-service
          uri: http://ip172-18-0-15-d65f9q291nsg00e23itg-8082.direct.labs.play-with-docker.com
          predicates:
            - Path=/ws/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server/.well-known/jwks.json

# Frontend Configuration
frontend:
  url: http://ip172-18-0-15-d65f9q291nsg00e23itg-3000.direct.labs.play-with-docker.com
  cors:
    allowed-origins: http://ip172-18-0-15-d65f9q291nsg00e23itg-3000.direct.labs.play-with-docker.com
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Content-Type,Authorization

logging:
  level:
    com.agarg.securecollab: DEBUG
